### ISSUE TITLE
A Rossetta4BIRD alternative to XCoreL (XCore with lineage extensions)

### ISSUE THREAD

**Issue by RBirdwatcher** [eclipse/efbt#1063]
We outline here the Eclipse Free BIRD Tools approach to providing data aware, developer friendly, tooling for use with BIRD. This tooling is based on ECore and XCoreL (which is XCore with some extensions). We discuss  if this approach could be replaced by Ecore and Rosetta4BIRD (i.e creating extensions to RossettaDSL to make it comparable with XCoreL)

Currently the BIRD project uses the commercial (but free of charge) Oracle SQLDeveloper tool to describe its data models, it has very little tools support for the regulatory transformations part of the BIRD project.

The Ecore standard would be a good replacement for storing the data models, given the similarity of existing mature Ecore tools to SQLDeveloper.  This project already provides a SQLDeveloper to Ecore translator showing that the concepts are transferable, and enables the tools to be used productively....however work would be more efficient and seamless if the BIRD data models were published in Ecore format, and this would greatly open up the field for further tools development which is much easier on these open standards than SQLDevelopers closed standards.

Ecore has an API which is a lot simpler than the SQLDeveloper API. As a small subset of the  SQLDeveloper Java API is used for BIRD Forward Engineering (A key part of the BIRD project) , so the simpler Ecore API could be used for the same purpose also (such a port is possible)…this is a relatively small change so is more likely to be adopted, it also opens up many possibilities for BIRD if  BIRD is  based on an open, developer friendly ,  standard for data modeling (such as tool availability, tool amendment, tool creation, clearer licensing, safer more predictable dependencies).

Eclipse XCore is a more human readable way of storing Ecore files (and is semantically equivalent to Ecore, we can translate to and from Xcore/Ecore without loss of information)…XCore can address some of the transformation/behavior part of BIRD not covered by SQLDeveloper). The executable part of XCore has a dependency on a language called XTend (sometimes known as XBase). Xbase is hard to use with the Language Server Protocol, which means it is limited in where it can be used, particularly it is hard to use in web-based frameworks.

XCoreL (XCore with Lineage extensions) is a language defined by this project to retain the advantages of XCore and overcome the limits imposed by XBase (by removing the dependency on XBase and replacing it with ability to use other languages like Python/Java/Scala) and adding  many useful features  for BIRD Transformations (alignment with the BIRD architecture, business friendly transformations, attribute lineage, data lineage, link to regulations, multi-step processing typical  in prudential reporting, visual workflow descriptions of complex prudential regulation, test descriptions suitable for good test coverage). XCoreL can be used to support the current banking transformation working groups of BIRD working on Finrep and Asset Encumberance who currently have very little tool support (and where data aware tools support is  very useful!). This project also currently provides tool support to help port an existing set of transformations and tests for Finrep 2.8 defined in VTL by the BIRD project into XCoreL using the latest BIRD data model, making use of a great body of work already created (and moving towards fully executable prototypes for real regulations on top of BIRD)

RosettaDSL, has some similarities to XCore and addresses the same concerns of both data modelling and transformation logic, and also avoids the use of XBase by having a language for describing logic which is usable with the Language Server Protocol, and therefore a number of web frameworks (including Github Codespaces )

So, an alternative to extending XCore (as XCoreL, XCore with Lineage extensions) is also to extend Rosetta (e.g. Rosetta4BIRD). In this case making a translator to and from Ecore to Rosetta4BIRD is useful so that the more mature Ecore standard can give a small migration path away from SQLDeveloper to the BIRD data modelling group (which is more likely to be accepted, than a compete switch to XCoreL or Rossetta4BIRD), and we can add the transformation logic to the Rossetta4BIRD files. BIRD could then be defined as 1 Ecore file, one visual layout file for the data model (such as a .aird file in Ecore tools), and one or more Rosetta4BIRD files (or XCoreL files) for transformations and tests.

We are already working on an Ecore to XCoreL translator, the extra information about transformation should be storable in Ecore annotations on EOperations. So an Ecore to Rosetta4BIRD file could be equally possible.

Some investigation into this has started, comments are welcome.

**Comment by minesh-s-patel** [comment]
@hugohills-regnosys @SimonCockx - What are your thoughts on this?

**Comment by RBirdwatcher** [comment]
@minesh-s-patel @hugohills-regnosys @SimonCockx I have started to make a port of this XCoreL [file ](https://github.com/eclipse/efbt/blob/feature_rossetta-integration/openregspecs/java_examples/plugins/org.eclipse.efbt.openregspecs.examples.core/examples/org.eclipse.efbt.example.frtb_cutdown/src/input_layer_entities.xcorel) related to complex FRTB prudential regulatory processing into this rosetta [file ](https://github.com/eclipse/efbt/blob/feature_rossetta-integration/openregspecs/java_examples/plugins/org.eclipse.efbt.openregspecs.examples.core/examples/org.eclipse.efbt.example.frtb_cutdown/frtb_wip.rosetta) ...its a work in progress...the FRTB data model is defined in SQLDeveloper as part of this project then converted to ecore, it uses the same standards as BIRD but is not yet part of BIRD.

**Comment by RBirdwatcher** [comment]
Out of scope as per  issue 1071, "remove executable component" [1071](https://github.com/eclipse/efbt/issues/1071)
