### ISSUE TITLE
linux issue displaying generated java files

### ISSUE THREAD

**Issue by RBirdwatcher** [eclipse/efbt#912]
testing in Linux (ubuntu) we see that directories of Java files can be displayed. However the list of generated JAva files (generated from ecore or XCore) displays really strangely o that we cannot choose an individual file to display

**Comment by Stmwkr** [comment]
Hello @RBirdwatcher , I finally got up some time, so am going to go through some of the issues. I wanted to reproduce the issue on my laptop (T470 with Fedora 39) and I successfully build the actual master onto my laptop. I was successful into installing efbt into my eclipse.
Hence I would like if possible to have the description of the issue in the following form : 

**Steps to reproduce : **

1. Step 1
2. ...

**Expected result : **
Lorem ipsum dolor sit amet, consectetur adipiscing elit.

**Actual result : ** 
Lorem ipsum dolor sit amet, consectetur adipiscing elit.

**System : **
Ubuntu (Version (?))
Eclipse (if impacted) Version ? -> on that note, we might want to tell users to install eclipse using the flatpak image flatpak install org.eclipse.Java to avoid dependency hell.

**Comment by RBirdwatcher** [comment]
Thanks @Stmwkr .

I will prepare some more detail for the issue.

For the missing license , do you mean the one in this file? https://github.com/eclipse/efbt/blob/master/sirius_ui/features/org.eclipse.efbt.regpot_desktop.sirius_ui.feature/feature.xml  . Like all Artefacts in this repository  it should be the Eclipse Public License version 2.

**Comment by Stmwkr** [comment]
@RBirdwatcher Hey !
For the licensing, I think that is it. I just saw it while going through the license agreements.
Thanks a lot in advance !

**Comment by RBirdwatcher** [comment]
I have created an issue for the missing license at https://github.com/eclipse/efbt/issues/1372

Regarding this Linux display issue I discovered a fix., so I describe the problem below for reference, and have closed the issue.

My Linux system is Ubuntu 23.10.

To use lineage visualization features you need to add the modelling project nature, this is currently being documented under https://github.com/eclipse/efbt/issues/1373 .

If a project has both the modelling nature and java nature, then display of any directories containing java files becomes strange on my Linux distro (maybe all Linux distros).

This is fixed by deleting the java nature form the .project file which is not needed.

So projects that can be used with the Eclipse Free BIRD Tools application , containing RegDNA files or XCore files, should not  have both a Java nature and modelling nature in the .project file.

The Linux version is very important to Eclipse Free BIRD Tools, especially because it allows for a web based version to be used via Apache Guacamole for institutions who have restrictions and long approval processes for installing desktop software. 

![Screenshot from 2024-06-11 11-09-58](https://github.com/eclipse/efbt/assets/32357922/61a11efb-52bd-4f75-9f69-48f73669b5f4)
![Screenshot from 2024-06-11 11-08-54](https://github.com/eclipse/efbt/assets/32357922/41dcbfa2-0024-4df0-b785-8db693bc5325)
